version: '2'
services:
  webserver:
    image: schoolimage
    build:
      context: ./
      dockerfile: Dockerfile    
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./app:/var/www/html/app
    depends_on:
      - db
    networks:
      - test
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=school
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3307:3307"
    networks:
      - test
networks:
  test:
    driver: bridge